# XOR
하나의 히든 레이어를 도입한다.<br>
input layer는 2개의 노드 + 1개의 바이어스<br>
hidden layer는 3개의 노드 + 1개의 바이어스<br>
output은 하나의 노드로 한다.

In [1]:
import numpy as np

In [2]:
X = [[0,0,1],[1,0,1],[0,1,1],[1,1,1]] # 세번째 항은 bias
y = [0,1,1,0]

위의 데이터를 neural networks에서 backpropagation을 이용하여으로 학습시켜라.

In [3]:
def f(x): 
    return 1/(1+np.exp(-x)) # sigmoid

inp, hid, outp = 3,4,1 # 3 input nodes,4 hidden nodes, a output node
np.random.seed(0) # 초기 w, omega 임의 결정 + 고정
w = 2*np.random.random((inp,hid))-1 # hidden nodes 만큼 random number, input nodes 만큼 반복, input 가중치
omega = 2*np.random.random((hid,outp))-1 # output nodes 만큼 random number, hidden nodes 만큼 반복, hidden 가중치

In [4]:
dh = [0,0,0,0] 
eta = 10
O = [] # 학습결과 
for n in range(10000):
    for i in range(len(X)): # 경우의 수 연산
        neth = np.dot(X[i],w) 
        h = f(neth) # neth sigmoid로 분류
        neto = np.dot(h,omega)
        o = f(neto) # neto sigmoid로 분류
        if (n==9999):
            O.append(o)
        do = (o-y[i])*f(neto)*(1-f(neto)) # d(sigmoid(x))/dx = (sigmoid(x))*(1-(sigmoid(x)))
        for j in range(hid): # hidden 가중치 변화
            dh[j] = do*omega[j]*f(neth[j])*(1-f(neth[j]))
            omega[j] += -eta*do*h[j]
            for k in range(inp): # input 가중치 변화
                w[k][j] += -eta*dh[j]*X[i][k]
O

[array([0.00137027]),
 array([0.99769303]),
 array([0.99665161]),
 array([0.00429128])]